modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://curseforge.com/minecraft/mc-mods/cbc-modern-warfare"
license = "MIT and CC BY-NC-SA (see github for details)"

[[mods]]
modId = "cbcmodernwarfare"
version = "${version}"
displayName = "CBC Modern Warfare"
authors = "riftyboi"
description = """Modern Warfare Is upon us
Attributions:
Textures by RiftyBoi, BedrockBetter, Brownboy. Original CBC Textures by rbasamoyai, Milkyfur, and LopyLuna
"""
logoFile = "icon.png"

[[dependencies.cbcmodernwarfare]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cbcmodernwarfare]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cbcmodernwarfare]]
modId = "create"
mandatory = true
versionRange="[${create_version},)"
ordering = "NONE"
side = "BOTH"
